# Generated by Django 3.2.1 on 2021-05-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documento_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='funcionario',
            new_name='pertence',
        ),
    ]
